services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Password1!
      POSTGRES_USER: dev
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
