\c dev;

create schema chat_service;

create table if not exists chat_service.user (
    id int generated by default as identity primary key,
    global_user_id text not null,
    "username" text not null
);

create table if not exists chat_service.chat (
    id int generated by default as identity primary key,
    created_at timestamp null default now()
);

create table if not exists chat_service.message (
    id int generated by default as identity primary key,
    sender_id int not null,
--     sender_global_user_id text not null,
    chat_id int not null,
    "timestamp" timestamp null default now(),
    message text not null,
    type text not null,

    constraint fk_user foreign key (sender_id) references chat_service.user (id),
    constraint fk_chat foreign key (chat_id) references chat_service.chat (id)
);

create table if not exists chat_service.user_chat (
    user_id int not null,
    chat_id int not null,

    constraint fk_user foreign key (user_id) references chat_service.user (id),
    constraint fk_chat foreign key (chat_id) references chat_service.chat (id),
    constraint pk_chat_user primary key (user_id, chat_id)
);
